# Generated by Django 2.2.5 on 2019-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('badge', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
