# Generated by Django 2.2.5 on 2019-10-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191015_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='badge',
            field=models.CharField(choices=[(0, 'primary'), (1, 'secondary'), (2, 'success'), (3, 'danger'), (4, 'warning'), (5, 'info'), (6, 'light'), (7, 'dark')], max_length=20),
        ),
    ]
